name: Push to SourceCraft

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to SourceCraft
        run: |
          git push https://oauth2:${{ secrets.SOURCECRAFT_TOKEN }}@sourcecraft.dev/d1jocker/portfolio.git main